### ISSUE TITLE
Not Work on 1.20.4

### ISSUE THREAD

**Issue by eslicarrillo** [Flemmli97/SimpleQuests#18]
### Modloader

Fabric

### Minecraft version

1.20.4

### Modloader version

1.15

### Mod version

1.20.1

### Description

The Mod not work on 1.20.4

### Steps to reproduce

run on 1.20.4

### Logs

[09:34:17 ERROR] [main]: [FabricLoader/Mixin] Mixin apply for mod simplequests failed simplequests.mixins.json:ServerPlayerMixin from mod simplequests -> net.minecraft.class_3222: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on initData could not find any targets matching 'Lnet/minecraft/class_3222;<init>(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;)V' in net.minecraft.class_3222. Using refmap simplequests-common-refmap.json [PREINJECT Applicator Phase -> simplequests.mixins.json:ServerPlayerMixin from mod simplequests -> Prepare Injections ->  -> handler$dlg000$simplequests$initData(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on initData could not find any targets matching 'Lnet/minecraft/class_3222;<init>(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;)V' in net.minecraft.class_3222. Using refmap simplequests-common-refmap.json [PREINJECT Applicator Phase -> simplequests.mixins.json:ServerPlayerMixin from mod simplequests -> Prepare Injections ->  -> handler$dlg000$simplequests$initData(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source) ~[?:?]

**Comment by Flemmli97** [comment]
1.20.4 is not supported
